language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - nvm install 12

before_script:
  - composer install
  - npm install

script:
  - composer cs

notifications:
  email: false
